version: "3.3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sns,sqs,s3,logs,cloudwatch,sts
      - DEFAULT_REGION=us-central-1
      - EDGE_PORT=4566
    ports:
      - "4566-4597:4566-4597"
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node app.js